export type InputProps = {
  autoComplete?: string;
  className?: string;
  disabled?: boolean;
  errorMessage?: string;
  floatingLabel?: string;
  hasError?: boolean;
  id: string;
  label?: string;
  leftBlock?: React.ReactNode;
  maxLength?: number;
  placeholder?: string;
  rightBlock?: React.ReactNode;
  rightBlockClassName?: string;
  style?: React.CSSProperties;
  type?: 'password' | 'text';
  value: string;
  onChange?: (e: React.ChangeEvent<HTMLInputElement>) => void;
  onFocus?: (e: React.FocusEvent<HTMLInputElement>) => void;
  onBlur?: (e: React.FocusEvent<HTMLInputElement>) => void;
  onClick?: (e: React.MouseEvent<HTMLInputElement>) => void;
  alwaysFocused?: boolean;
};
