
export enum IconsEnum {
  // account
  shield = '/icons/account/shield.svg',
  guide = '/icons/account/guide.svg',
  email = '/icons/account/email.svg',
  sms = '/icons/account/sms.svg',

  // common
  adminPanel = '/icons/common/admin-panel.svg',
  aiAssit = '/icons/common/ai-assist-icon.svg',
  alert = '/icons/common/alert.svg',
  alertCircle = '/icons/common/alert-circle.svg',
  alertTriangle = '/icons/common/alert-triangle.svg',
  announcement = '/icons/common/announcement.svg',
  arrow = '/icons/common/arrow.svg',
  arrowChevron = '/icons/common/arrow-chevron.svg',
  arrowDown = '/icons/common/arrow-down.svg',
  arrowRight = '/icons/common/arrow-right.svg',
  arrowUp = '/icons/common/arrow-up.svg',
  award = '/icons/common/award.svg',
  bell = '/icons/common/bell.svg',
  chart = '/icons/common/chart-icon.svg',
  check = '/icons/common/check.svg',
  checkboxV = '/icons/common/checkbox-v.svg',
  checkCircle = '/icons/common/check-circle.svg',
  checkCircleBlue = '/icons/common/checkCircleBlue.svg',
  circleArrows = '/icons/common/circle-arrows.svg',
  clock = '/icons/common/clock.svg',
  config = '/icons/common/config.svg',
  copy = '/icons/common/copy.svg',
  cross = '/icons/common/cross.svg',
  cube = '/icons/common/cube.svg',
  data = '/icons/common/data.svg',
  delete = '/icons/common/delete.svg',
  dollar = '/icons/common/dollar.svg',
  done = '/icons/common/done.svg',
  edit = '/icons/common/edit.svg',
  editPencil = '/icons/common/edit-pencil.svg',
  envelope = '/icons/common/envelope.svg',
  file = '/icons/common/file.svg',
  filePlus = '/icons/common/file-plus.svg',
  filter = '/icons/common/filter.svg',
  font = '/icons/common/font.svg',
  grid = '/icons/common/grid.svg',
  help = '/icons/common/help.svg',
  hidePassowrd = '/icons/common/hide-password.svg',
  image = '/icons/common/image.svg',
  lifeBuoy = '/icons/common/life-buoy.svg',
  lineChartUp = '/icons/common/line-chart-up.svg',
  loader = '/icons/common/loader.svg',
  lock = '/icons/common/lock.svg',
  minus = '/icons/common/minus.svg',
  minusCircle = '/icons/common/minus-circle.svg',
  mobile = '/icons/common/mobile.svg',
  moda = '/icons/common/moda.svg',
  monitor = '/icons/common/monitor.svg',
  moreHorizontal = '/icons/common/more-horizontal.svg',
  paperClip = '/icons/common/paper-clip.svg',
  pause = '/icons/common/pause.svg',
  person = '/icons/common/person.svg',
  phone = '/icons/common/phone.svg',
  pie = '/icons/common/pie.svg',
  play = '/icons/common/play.svg',
  plus = '/icons/common/plus.svg',
  plusInCircle = '/icons/common/plus-in-circle.svg',
  publish = '/icons/common/publish.svg',
  save = '/icons/common/save.svg',
  search = '/icons/common/search.svg',
  showPassword = '/icons/common/show-password.svg',
  slash = '/icons/common/slash.svg',
  star = '/icons/common/star.svg',
  switchHorizontal = '/icons/common/switch-horizontal.svg',
  tag = '/icons/common/tag.svg',
  trendDown = '/icons/common/trend-down.svg',
  upload = '/icons/common/upload-cloud.svg',
  uploadDefault = '/icons/common/upload.svg',
  userPlus = '/icons/common/user-plus.svg',
  users = '/icons/common/users.svg',
  video = '/icons/common/video.svg',

  // campaigns
  draft = '/icons/campaigns/draft.svg',
  scheduled = '/icons/campaigns/Scheduled.svg',
  sending = '/icons/campaigns/Sending.svg',
  complete = '/icons/campaigns/Sent.svg',
  sent = '/icons/campaigns/Sent.svg',
  archived = '/icons/campaigns/Archived.svg',
  mail = '/icons/campaigns/mail.svg',
  message = '/icons/campaigns/message.svg',
  cancel = '/icons/campaigns/cancel.svg',

  refresh = '/icons/common/refresh-cw.svg',
  glob = '/icons/common/globe.svg',
  info = '/icons/common/info.svg',

  // forms

  formsIcon = '/icons/forms/forms.svg',
  load = '/icons/forms/load.svg',
  exit = '/icons/forms/exit.svg',
  scroll = '/icons/forms/scroll.svg',

  // menu
  automate = '/icons/menu/automate.svg',
  dashboard = '/icons/menu/dashboard.svg',
  integrate = '/icons/menu/integrate.svg',
  manage = '/icons/menu/manage.svg',
  settings = '/icons/menu/settings.svg',
  support = '/icons/common/help.svg',

  gettingStarted = '/icons/menu/getting-started.svg',
  videoTutorials = '/icons/menu/video-tutorials.svg',
  reportBug = '/icons/menu/report-bug.svg',
  requestFeature = '/icons/menu/request-feature.svg',
  changeLog = '/icons/menu/change-log.svg',
  documentation = '/icons/menu/documentation.svg',
  chatSupport = '/icons/menu/chat-support.svg',

  apiKey = '/icons/menu/api-key.svg',
  notificationSettings = '/icons/menu/notification-settings.svg',
  roles = '/icons/menu/roles.svg',
  messagingSetup = '/icons/menu/messaging-setup.svg',
  dataDictionary = '/icons/menu/data-dictionary.svg',

  account = '/icons/menu/account.svg',
  billing = '/icons/menu/billing.svg',
  logout = '/icons/menu/log-out.svg',

  // integrations
  google = '/icons/integrations/google.svg',

  // segments
  event = '/icons/segments/event.svg',
  attribute = '/icons/segments/attribute.svg',
  segment = '/icons/segments/segment.svg',
  shopifyGrayscale = '/icons/segments/shopify-grayscale.svg',
  occurs = '/icons/segments/occurs.svg',
  firstOccurred = '/icons/segments/first-occured.svg',
  lastOccurred = '/icons/segments/last-occured.svg',
  shopify = '/icons/common/shopify.svg',
  calendar = '/icons/segments/calendar.svg',

  // change password
  key = '/icons/changePassword/key.svg',

  //flags
  indonesia = '/icons/flags/Indonesia.svg',

  // flows
  rocket = '/icons/flows/rocket.svg',
  lightning = '/icons/flows/lightning.svg',
  chevrons = '/icons/flows/chevrons-right.svg',
  addTag = '/icons/flows/add-tag.svg',
  removeTag = '/icons/flows/remove-tag.svg',
  forms = '/icons/flows/forms.svg',
  messageSquare = '/icons/flows/message-square.svg',
  mailSquare = '/icons/flows/mail-square.svg',
  server = '/icons/flows/server.svg',
  smartphone = '/icons/flows/smartphone.svg',
  addSegment = '/icons/flows/add-segment.svg',
  removeSegment = '/icons/flows/remove-segment.svg',
  facebookAdd = '/icons/flows/facebook-add.svg',
  facebookRemove = '/icons/flows/facebook-remove.svg',
  splitPath = '/icons/flows/split-path.svg',
  trueFalse = '/icons/flows/true-false.svg',
  percentageSplit = '/icons/flows/random-percentage-split.svg',
  waitCondition = '/icons/flows/wait-condition.svg',
  waitDuration = '/icons/flows/wait-duration.svg',
  waitTimeWindow = '/icons/flows/wait-time-window.svg',
  sendToFlow = '/icons/flows/send-to-flow.svg',
  exitSegment = '/icons/flows/exit-segment.svg',

  // Networks
  twitter = '/icons/networks/twitter.svg',
  facebook = '/icons/networks/facebook.svg',
  instagram = '/icons/networks/instagram.svg',
  linkedin = '/icons/networks/linkedin.svg',
  tiktok = '/icons/networks/tiktok.svg',
  youtube = '/icons/networks/youtube.svg',
  twitterOutline = '/icons/networks/twitter_outline.svg',
  facebookOutline = '/icons/networks/facebook_outline.svg',
  instagramOutline = '/icons/networks/instagram_outline.svg',
  linkedinOutline = '/icons/networks/linkedin_outline.svg',
  tiktokOutline = '/icons/networks/tiktok_outline.svg',
  youtubeOutline = '/icons/networks/youtube_outline.svg',
}

export type SvgIconProps = {
  src: IconsEnum;
  onClick?: () => void;
  size?: number;
  rotate?: '0' | '90' | '180' | '270';
  className?: string;
  style?: React.CSSProperties;
};
